import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-brand h-12 items-center flex fixed w-screen">
        <div className="container mx-auto text-lg px-2">Activities</div>
      </div>
      <main className="flex bg-white flex-col px-2 dark:bg-black dark:text-white gap-3">
        <div className="h-12"></div>
        <div className="container mx-auto flex-1">
          <h2 className="text-5xl">Activities</h2>
        </div>
      </main>
    </>
  )
}

export default Home
